language: ruby
rvm:
  - 2.2.4
bundler_args: "--without development --without production --deployment"
cache: bundler
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - "rvm @global do gem uninstall bundler -x && gem install bundler"
before_script:
  - 'npm install'
  - 'bundle exec rake db:create:all'
  - 'bundle exec rake db:migrate'
script:
  - "PATH=$PWD/frontend/node_modules/phantomjs-prebuilt/bin:$PATH bundle exec rake"

sudo: false
