language: ruby
rvm:
  - 2.3.1
bundler_args: "--without development --without production --deployment"
cache: bundler
env:
  - "PATH=$PWD/frontend/node_modules/.bin:$PATH"
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - "rvm @global do gem uninstall bundler -x && gem install bundler"
before_script:
  - 'nvm install 5'
  - 'npm install'
  - 'bundle exec rake db:create:all'
  - 'bundle exec rake db:migrate'
script:
  - "bundle exec rake rspec_with_retries"
  - "bundle exec rake ember:test"

sudo: false
